import {
  BarChart3,
  ClipboardCheck,
  ClipboardList,
  PackageCheck,
  PackagePlus,
  Receipt,
  Truck,
  Undo2,
  WalletCards,
} from "lucide-react";

export const purchasesHubConfig = {
  id: "purchases",
  title: "Xaridlar",
  description: "Xarid buyurtmalari, qabul, invoys va xarid nazoratini boshqarish.",
  sections: [
    {
      id: "orders",
      title: "Buyurtmalar",
      items: [
        {
          id: "purchase-orders",
          title: "Xarid buyurtmalari",
          description: "Barcha purchase orderlarni ko'rish va boshqarish.",
          icon: ClipboardList,
          route: "/purchases/orders",
          permission: { key: "po.view", fallback: "disabled" },
          order: 1,
        },
        {
          id: "purchase-new-order",
          title: "Yangi xarid buyurtmasi",
          description: "Supplier va mahsulotlar asosida yangi buyurtma yaratish.",
          icon: PackagePlus,
          route: "/purchases/orders/new",
          permission: { key: "po.create", fallback: "disabled" },
          order: 2,
        },
        {
          id: "purchase-today-arrivals",
          title: "Yetib keladiganlar",
          description: "Qabul rejalari va buyurtmalar.",
          icon: Truck,
          route: "/purchases/orders?delivery=today",
          permission: { key: "po.view", fallback: "disabled" },
          order: 3,
        },
      ],
    },
    {
      id: "receiving",
      title: "Qabul va to'lov",
      items: [
        {
          id: "purchase-receiving",
          title: "Tovar qabul qilish",
          description: "Kelgan mahsulotlarni miqdor, narx va hujjatlar bilan qabul qilish.",
          icon: PackageCheck,
          route: "/purchases/receiving",
          permission: { key: "receiving.create", fallback: "disabled" },
          order: 1,
        },
        {
          id: "purchase-quality",
          title: "Sifat tekshiruvi",
          description: "Qabuldan keyingi sifat nazorati va tekshiruvlar.",
          icon: ClipboardCheck,
          route: "/purchases/quality-inspection",
          permission: { key: "receiving.create", fallback: "disabled" },
          order: 2,
        },
        {
          id: "purchase-invoices",
          title: "Invoyslar va to'lovlar",
          description: "Supplier invoyslari, muddatlar va to'lovlarni kuzatish.",
          icon: Receipt,
          route: "/purchases/invoices",
          permission: { key: "invoice.create", fallback: "disabled" },
          order: 3,
        },
        {
          id: "purchase-returns",
          title: "Qaytarishlar",
          description: "Qabul qilingan mahsulotlar bo'yicha qaytarish jarayoni.",
          icon: Undo2,
          route: "/purchases/returns",
          permission: { key: "return.create", fallback: "disabled" },
          order: 4,
        },
      ],
    },
    {
      id: "management",
      title: "Boshqaruv",
      items: [
        {
          id: "purchase-budgets",
          title: "Byudjetlar",
          description: "Xarid byudjetlari va limitlarni boshqarish.",
          icon: WalletCards,
          route: "/purchases/reports",
          permission: { key: "reports.view", fallback: "disabled" },
          order: 1,
        },
        {
          id: "purchase-reports",
          title: "Xarid tahlili",
          description: "Supplier xarajatlari, narxlar va buyurtmalar dinamikasi.",
          icon: BarChart3,
          route: "/purchases/reports",
          permission: { key: "reports.view", fallback: "disabled" },
          order: 2,
        },
      ],
    },
  ],
};
