// Demo boshlang'ich bildirishnomalar — mavjud purchaseSeed.js/suppliersApi.js
// yozuvlariga (PO/Invoys/Qaytarish/Supplier) ishora qiladi, shu sabab
// Notification Center birinchi ochilishda bo'sh emas, real workflow holatini
// aks ettiradi. To'lov muddati/byudjet kabi VAQTGA BOG'LIQ ogohlantirishlar
// bu yerda YOZILMAYDI — ular useNotificationsSync tomonidan joriy sanaga
// nisbatan HAR DOIM qayta hisoblanadi (masalan INV-2026-3003 allaqachon
// muddati o'tgan — sync uni avtomatik "To'lov muddati o'tib ketdi" qiladi).

import { NOTIFICATION_TYPES } from "./notificationTypes";
import { NOTIFICATION_PRIORITIES } from "./notificationPriority";
import { NOTIFICATION_STATUSES } from "./notificationStatus";

export const SEED_NOTIFICATIONS = [
  {
    id: "ntf-seed-1",
    type: NOTIFICATION_TYPES.poSubmitted,
    priority: NOTIFICATION_PRIORITIES.medium,
    status: NOTIFICATION_STATUSES.unread,
    title: "Buyurtma tasdiqqa yuborildi",
    message:
      "PO-2026-1003 (Global Import LLC) moliya bo'limi tasdig'ini kutmoqda.",
    link: "/purchases/orders/po-1003",
    refs: { orderId: "po-1003", orderNumber: "PO-2026-1003", supplierId: "sup-global" },
    actor: "Dilshod Raximov",
    source: "event",
    dedupeKey: "po_submitted:po-1003",
    createdAt: "2026-07-14T10:30:00.000Z",
    readAt: null,
    archivedAt: null,
    dismissedAt: null,
  },
  {
    id: "ntf-seed-2",
    type: NOTIFICATION_TYPES.invoiceMismatch,
    priority: NOTIFICATION_PRIORITIES.high,
    status: NOTIFICATION_STATUSES.unread,
    title: "Invoys nomuvofiqligi",
    message:
      "INV-2026-3003 (AgroFood Distribution) uch tomonlama solishtiruvda nomuvofiqlik aniqlandi.",
    link: "/purchases/invoices",
    refs: { invoiceId: "inv-3003", invoiceNumber: "INV-2026-3003", orderId: "po-1002", supplierId: "sup-agrofood" },
    actor: "Nilufar Sobirova",
    source: "event",
    dedupeKey: "invoice_mismatch:inv-3003",
    createdAt: "2026-07-08T12:05:00.000Z",
    readAt: null,
    archivedAt: null,
    dismissedAt: null,
  },
  {
    id: "ntf-seed-3",
    type: NOTIFICATION_TYPES.purchaseReturn,
    priority: NOTIFICATION_PRIORITIES.medium,
    status: NOTIFICATION_STATUSES.unread,
    title: "Qaytarish tasdiq kutmoqda",
    message: "RET-2026-4002 — buzilgan tovar sababli qaytarish so'raldi (285 000 so'm).",
    link: "/purchases/returns",
    refs: { returnId: "ret-4002", returnNumber: "RET-2026-4002", orderId: "po-1002", supplierId: "sup-agrofood" },
    actor: "Olim Tashev",
    source: "event",
    dedupeKey: "purchase_return:ret-4002",
    createdAt: "2026-07-11T10:15:00.000Z",
    readAt: null,
    archivedAt: null,
    dismissedAt: null,
  },
  {
    id: "ntf-seed-4",
    type: NOTIFICATION_TYPES.goodsReceived,
    priority: NOTIFICATION_PRIORITIES.low,
    status: NOTIFICATION_STATUSES.read,
    title: "Tovar to'liq qabul qilindi",
    message: "PO-2026-1005 (Samarqand Non Kombinati) bo'yicha barcha tovar qabul qilindi.",
    link: "/purchases/orders/po-1005",
    refs: { orderId: "po-1005", orderNumber: "PO-2026-1005", supplierId: "sup-samarqand" },
    actor: "Olim Tashev",
    source: "event",
    dedupeKey: "goods_received:po-1005",
    createdAt: "2026-07-04T09:00:00.000Z",
    readAt: "2026-07-04T09:20:00.000Z",
    archivedAt: null,
    dismissedAt: null,
  },
  {
    id: "ntf-seed-5",
    type: NOTIFICATION_TYPES.paymentCreated,
    priority: NOTIFICATION_PRIORITIES.low,
    status: NOTIFICATION_STATUSES.read,
    title: "To'lov amalga oshirildi",
    message: "INV-2026-3002 (Toshkent Sut Mahsulotlari) to'liq to'landi.",
    link: "/purchases/invoices",
    refs: { invoiceId: "inv-3002", invoiceNumber: "INV-2026-3002", supplierId: "sup-toshkent-sut" },
    actor: "Nilufar Sobirova",
    source: "event",
    dedupeKey: "payment_created:inv-3002:pay-2",
    createdAt: "2026-06-25T15:30:00.000Z",
    readAt: "2026-06-26T08:00:00.000Z",
    archivedAt: null,
    dismissedAt: null,
  },
  {
    id: "ntf-seed-6",
    type: NOTIFICATION_TYPES.supplierIssue,
    priority: NOTIFICATION_PRIORITIES.high,
    status: NOTIFICATION_STATUSES.read,
    title: "Yetkazib beruvchida muammo",
    message: "Global Import LLC: oxirgi 3 oyda narx 15% oshdi — muqobil supplier ko'rib chiqilsin.",
    link: "/suppliers/sup-global",
    refs: { supplierId: "sup-global" },
    actor: "Aziz Karimov",
    source: "event",
    dedupeKey: "supplier_issue:sup-global:note-global-1",
    createdAt: "2026-06-15T09:05:00.000Z",
    readAt: "2026-06-15T10:00:00.000Z",
    archivedAt: null,
    dismissedAt: null,
  },
  {
    id: "ntf-seed-7",
    type: NOTIFICATION_TYPES.supplierIssue,
    priority: NOTIFICATION_PRIORITIES.critical,
    status: NOTIFICATION_STATUSES.archived,
    title: "Yetkazib beruvchida muammo",
    message: "Eski Savdo MChJ: bir necha marta buzuq tovar yetkazdi — sifat nazorati muvaffaqiyatsiz, supplier bloklandi.",
    link: "/suppliers/sup-blocked",
    refs: { supplierId: "sup-blocked" },
    actor: "Aziz Karimov",
    source: "event",
    dedupeKey: "supplier_issue:sup-blocked:note-blocked-1",
    createdAt: "2026-05-01T09:05:00.000Z",
    readAt: "2026-05-01T09:30:00.000Z",
    archivedAt: "2026-05-02T09:00:00.000Z",
    dismissedAt: null,
  },
  {
    id: "ntf-seed-8",
    type: NOTIFICATION_TYPES.systemNotification,
    priority: NOTIFICATION_PRIORITIES.informational,
    status: NOTIFICATION_STATUSES.dismissed,
    title: "Bildirishnomalar markazi faollashtirildi",
    message: "Xaridlar va Yetkazib beruvchilar moduli uchun Enterprise bildirishnoma tizimi ishga tushirildi.",
    link: null,
    refs: {},
    actor: "Tizim",
    source: "system",
    dedupeKey: null,
    createdAt: "2026-07-20T08:00:00.000Z",
    readAt: "2026-07-20T08:00:00.000Z",
    archivedAt: null,
    dismissedAt: "2026-07-20T08:05:00.000Z",
  },
];
