import {
  Banknote,
  BarChart3,
  CircleDollarSign,
  CreditCard,
  FileClock,
  FileText,
  Landmark,
  ListChecks,
  Receipt,
  Scale,
  ShieldCheck,
  TrendingDown,
  TrendingUp,
  WalletCards,
} from "lucide-react";

import { FINANCE_ACTION } from "../constants/financeConstants";

export const financeHubConfig = {
  id: "finance",
  title: "Moliya",
  description: "Pul harakati, bank, qarzdorlik va buxgalteriya nazoratini alohida yo'nalishlarda boshqarish.",
  sections: [
    {
      id: "cash-flow",
      title: "Pul harakati",
      items: [
        {
          id: "finance-overview",
          title: "Moliya overview",
          description: "Moliyaviy holat va asosiy ko'rsatkichlarni ko'rish.",
          icon: WalletCards,
          route: "/finance/overview",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 1,
        },
        {
          id: "finance-transactions",
          title: "Tranzaksiyalar",
          description: "Barcha moliyaviy operatsiyalar tarixini ko'rish.",
          icon: Receipt,
          route: "/finance/transactions",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 2,
        },
        {
          id: "finance-income",
          title: "Daromadlar",
          description: "Daromad tranzaksiyalari va tushum manbalarini boshqarish.",
          icon: TrendingUp,
          route: "/finance/income",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 3,
        },
        {
          id: "finance-expenses",
          title: "Xarajatlar",
          description: "Operatsion va boshqa xarajatlarni boshqarish.",
          icon: TrendingDown,
          route: "/finance/expenses",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 4,
        },
        {
          id: "finance-cash-flow",
          title: "Pul oqimi",
          description: "Kirim va chiqimlarning real harakatini kuzatish.",
          icon: CircleDollarSign,
          route: "/finance/cash-flow",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 5,
        },
      ],
    },
    {
      id: "bank-cash",
      title: "Bank va kassa",
      items: [
        {
          id: "finance-bank-accounts",
          title: "Bank hisoblari",
          description: "Bank hisoblari, qoldiq va operatsiyalarni boshqarish.",
          icon: Landmark,
          route: "/finance/bank-accounts",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 1,
        },
        {
          id: "finance-cash-accounts",
          title: "Kassa hisoblari",
          description: "Naqd pul kassalari va ularning harakatlarini boshqarish.",
          icon: Banknote,
          route: "/finance/cash-accounts",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 2,
        },
        {
          id: "finance-reconciliation",
          title: "Bank sverkasi",
          description: "Bank ma'lumotlari va tizim tranzaksiyalarini solishtirish.",
          icon: ShieldCheck,
          route: "/finance/reconciliation",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 3,
        },
        {
          id: "finance-payment-orders",
          title: "To'lov topshiriqlari",
          description: "Chiquvchi to'lovlarni yaratish, tasdiqlash va kuzatish.",
          icon: FileClock,
          route: "/finance/payment-orders",
          permission: { key: FINANCE_ACTION.CREATE, fallback: "disabled" },
          order: 4,
        },
      ],
    },
    {
      id: "debt-accounting",
      title: "Qarzdorlik va hisobot",
      items: [
        {
          id: "finance-receivables",
          title: "Debitorlik",
          description: "Mijozlarning to'lanmagan qarzlarini boshqarish.",
          icon: CreditCard,
          route: "/finance/receivables",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 1,
        },
        {
          id: "finance-payables",
          title: "Kreditorlik",
          description: "Supplier va boshqa majburiyatlarni boshqarish.",
          icon: ListChecks,
          route: "/finance/payables",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 2,
        },
        {
          id: "finance-profit-loss",
          title: "Profit and Loss",
          description: "Daromad, xarajat va foyda hisobotini ko'rish.",
          icon: BarChart3,
          route: "/finance/profit-loss",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 3,
        },
        {
          id: "finance-balance-sheet",
          title: "Balance Sheet",
          description: "Aktiv, majburiyat va kapital holatini ko'rish.",
          icon: Scale,
          route: "/finance/balance-sheet",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 4,
        },
        {
          id: "finance-cash-flow-statement",
          title: "Cash Flow Statement",
          description: "Moliyaviy pul oqimi hisobotini alohida ko'rish.",
          icon: FileText,
          route: "/finance/cash-flow-statement",
          permission: { key: FINANCE_ACTION.VIEW, fallback: "disabled" },
          order: 5,
        },
      ],
    },
  ],
};
