import {
  Activity,
  BarChart3,
  Database,
  FileUp,
  Gem,
  GitBranch,
  Megaphone,
  Settings,
  Tags,
  UserPlus,
  Users,
} from "lucide-react";

export const createCrmHubConfig = () => ({
  id: "crm",
  title: "CRM",
  description: "Mijozlar, segmentlar va mijoz bilan ishlash yo'nalishlari.",
  sections: [
    {
      id: "customers",
      items: [
        {
          id: "crm-customers",
          title: "Mijozlar bazasi",
          description: "Mijoz profillari va aloqalar.",
          icon: Users,
          route: "/crm/customers",
          permission: "crm.customers.view",
          order: 1,
        },
        {
          id: "crm-new-customer",
          title: "Yangi mijoz",
          description: "Yangi mijoz profilini yaratish.",
          icon: UserPlus,
          route: "/crm/customers/new",
          permission: "crm.customers.create",
          order: 2,
        },
        {
          id: "crm-segments",
          title: "Segmentlar",
          description: "Mijoz guruhlari va shartlar.",
          icon: Tags,
          route: "/crm/marketing/segments",
          permission: "crm.segments.view",
          order: 3,
        },
        {
          id: "crm-pipeline",
          title: "Pipeline",
          description: "Savdo bosqichlari va imkoniyatlar.",
          icon: GitBranch,
          route: "/crm/pipeline",
          permission: "crm.pipeline.view",
          order: 4,
        },
        {
          id: "crm-activities",
          title: "Faoliyatlar",
          description: "Qo'ng'iroq, uchrashuv va vazifalar.",
          icon: Activity,
          route: "/crm/activities",
          permission: "crm.activities.view",
          order: 5,
        },
        {
          id: "crm-campaigns",
          title: "Kampaniyalar",
          description: "Marketing kampaniyalari.",
          icon: Megaphone,
          route: "/crm/marketing/campaigns",
          permission: "crm.campaigns.view",
          order: 6,
        },
        {
          id: "crm-loyalty",
          title: "Loyalty",
          description: "Bonus va sodiqlik dasturlari.",
          icon: Gem,
          route: "/crm/loyalty",
          permission: "crm.loyalty.view",
          order: 7,
        },
        {
          id: "crm-dashboard",
          title: "CRM overview",
          description: "CRM umumiy ko'rinishi.",
          icon: Database,
          route: "/crm/dashboard",
          permission: "crm.view",
          order: 8,
        },
        {
          id: "crm-analytics",
          title: "CRM analytics",
          description: "Mijoz va savdo tahlili.",
          icon: BarChart3,
          route: "/crm/analytics",
          permission: {
            key: "crm.analytics.view",
            fallback: "approvalRequired",
            reason: "CRM tahlillarini ochish uchun rahbar tasdig'i kerak.",
          },
          order: 9,
        },
        {
          id: "crm-import-export",
          title: "Import va eksport",
          description: "Mijoz fayllari bilan ishlash.",
          icon: FileUp,
          route: "/crm/customers?panel=import-export",
          permission: "crm.customers.view",
          order: 10,
        },
        {
          id: "crm-settings",
          title: "CRM settings",
          description: "CRM qoidalari va sozlamalari.",
          icon: Settings,
          route: "/crm/settings",
          permission: "crm.settings.view",
          order: 11,
        },
      ],
    },
  ],
});
