import {
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpFromLine,
  BarChart3,
  ClipboardCheck,
  FileText,
  MapPinned,
  PackageSearch,
  Settings,
  Warehouse,
} from "lucide-react";

export const warehouseHubConfig = {
  id: "warehouse",
  title: "Ombor",
  description: "Omborlar, qoldiq, harakatlar va inventarizatsiya jarayonlarini boshqarish.",
  sections: [
    {
      id: "stock",
      title: "Qoldiq",
      items: [
        {
          id: "warehouse-list",
          title: "Omborlar",
          description: "Barcha omborlar va ularning holatini boshqarish.",
          icon: Warehouse,
          route: "/warehouse/warehouses",
          permission: { key: "view", fallback: "disabled" },
          order: 1,
        },
        {
          id: "warehouse-stock",
          title: "Qoldiq holati",
          description: "Mavjud, band va kam qolgan qoldiqlarni ko'rish.",
          icon: PackageSearch,
          route: "/warehouse/stock",
          permission: { key: "view", fallback: "disabled" },
          order: 2,
        },
        {
          id: "warehouse-movements",
          title: "Ombor harakatlari",
          description: "Kirim, chiqim, transfer va boshqa harakatlar tarixi.",
          icon: FileText,
          route: "/warehouse/movements",
          permission: { key: "view", fallback: "disabled" },
          order: 3,
        },
      ],
    },
    {
      id: "operations",
      title: "Operatsiyalar",
      items: [
        {
          id: "warehouse-receipts",
          title: "Kirim",
          description: "Omborga mahsulot qabul qilish.",
          icon: ArrowDownToLine,
          route: "/warehouse/receipts",
          permission: { key: "receipt", fallback: "disabled" },
          order: 1,
        },
        {
          id: "warehouse-issues",
          title: "Chiqim",
          description: "Ombordan mahsulot chiqarish va sababini audit qilish.",
          icon: ArrowUpFromLine,
          route: "/warehouse/issues",
          permission: { key: "issue", fallback: "disabled" },
          order: 2,
        },
        {
          id: "warehouse-transfers",
          title: "Ko'chirish",
          description: "Mahsulotlarni omborlar orasida ko'chirish.",
          icon: ArrowLeftRight,
          route: "/warehouse/transfers",
          permission: { key: "transfer", fallback: "disabled" },
          order: 3,
        },
        {
          id: "warehouse-inventory",
          title: "Inventarizatsiya",
          description: "Qoldiqlarni sanash va farqlarni tekshirish.",
          icon: ClipboardCheck,
          route: "/warehouse/inventory",
          permission: { key: "counting", fallback: "disabled" },
          order: 4,
        },
      ],
    },
    {
      id: "management",
      title: "Boshqaruv",
      items: [
        {
          id: "warehouse-tracking",
          title: "Kuzatuv",
          description: "Partiya, seriya, yaroqlilik muddati va lokatsiyalar.",
          icon: MapPinned,
          route: "/warehouse/tracking",
          permission: { key: "view", fallback: "disabled" },
          order: 1,
        },
        {
          id: "warehouse-analytics",
          title: "Warehouse analitika",
          description: "Aylanish, dead stock va ombor samaradorligi.",
          icon: BarChart3,
          route: "/warehouse/analytics",
          permission: { key: "view", fallback: "disabled" },
          order: 2,
        },
        {
          id: "warehouse-settings",
          title: "Ombor sozlamalari",
          description: "Hisobot, import/export, ruxsat va audit sozlamalari.",
          icon: Settings,
          route: "/warehouse/reports",
          permission: { key: "settings", fallback: "disabled" },
          order: 3,
        },
      ],
    },
  ],
};
