import { MODULE_IDS } from "./modules";

export const BUSINESS_TYPE_IDS = {
  retail: "retail",
  food: "food",
  production: "production",
  pharmacy: "pharmacy",
  education: "education",
  service: "service",
  hotel: "hotel",
  clinic: "clinic",
};

export const businessTypes = {
  [BUSINESS_TYPE_IDS.retail]: {
    id: BUSINESS_TYPE_IDS.retail,
    title: "Savdo",
    description:
      "Do‘kon, minimarket, kiyim-kechak, texnika va umumiy savdo bizneslari.",
    workspaceLabel: "Savdo paneli",
    primaryModule: MODULE_IDS.pos,
    modules: [
      MODULE_IDS.dashboard,
      MODULE_IDS.pos,
      MODULE_IDS.products,
      MODULE_IDS.inventory,
      MODULE_IDS.purchases,
      MODULE_IDS.crm,
      MODULE_IDS.suppliers,
      MODULE_IDS.finance,
      MODULE_IDS.reports,
      MODULE_IDS.hr,
      MODULE_IDS.integrations,
      MODULE_IDS.ai,
      MODULE_IDS.settings,
    ],
    dashboardType: "retail",
  },

  [BUSINESS_TYPE_IDS.food]: {
    id: BUSINESS_TYPE_IDS.food,
    title: "Ovqatlanish",
    description: "Kafe, restoran, fast food, oshxona va delivery bizneslari.",
    workspaceLabel: "Restoran paneli",
    primaryModule: MODULE_IDS.pos,
    modules: [
      MODULE_IDS.dashboard,
      MODULE_IDS.pos,
      MODULE_IDS.products,
      MODULE_IDS.inventory,
      MODULE_IDS.purchases,
      MODULE_IDS.crm,
      MODULE_IDS.suppliers,
      MODULE_IDS.finance,
      MODULE_IDS.reports,
      MODULE_IDS.hr,
      MODULE_IDS.recipe,
      MODULE_IDS.tables,
      MODULE_IDS.integrations,
      MODULE_IDS.ai,
      MODULE_IDS.settings,
    ],
    dashboardType: "food",
  },

  [BUSINESS_TYPE_IDS.production]: {
    id: BUSINESS_TYPE_IDS.production,
    title: "Ishlab chiqarish",
    description:
      "Xomashyo, ishlab chiqarish jarayoni va tayyor mahsulot nazorati.",
    workspaceLabel: "Ishlab chiqarish paneli",
    primaryModule: MODULE_IDS.production,
    modules: [
      MODULE_IDS.dashboard,
      MODULE_IDS.production,
      MODULE_IDS.products,
      MODULE_IDS.inventory,
      MODULE_IDS.purchases,
      MODULE_IDS.crm,
      MODULE_IDS.suppliers,
      MODULE_IDS.finance,
      MODULE_IDS.reports,
      MODULE_IDS.hr,
      MODULE_IDS.integrations,
      MODULE_IDS.ai,
      MODULE_IDS.settings,
    ],
    dashboardType: "production",
  },

  [BUSINESS_TYPE_IDS.pharmacy]: {
    id: BUSINESS_TYPE_IDS.pharmacy,
    title: "Apteka",
    description: "Dorilar, yaroqlilik muddati, savdo va ombor nazorati.",
    workspaceLabel: "Apteka paneli",
    primaryModule: MODULE_IDS.pos,
    modules: [
      MODULE_IDS.dashboard,
      MODULE_IDS.pos,
      MODULE_IDS.medicines,
      MODULE_IDS.inventory,
      MODULE_IDS.purchases,
      MODULE_IDS.crm,
      MODULE_IDS.suppliers,
      MODULE_IDS.finance,
      MODULE_IDS.reports,
      MODULE_IDS.hr,
      MODULE_IDS.integrations,
      MODULE_IDS.ai,
      MODULE_IDS.settings,
    ],
    dashboardType: "pharmacy",
  },

  [BUSINESS_TYPE_IDS.education]: {
    id: BUSINESS_TYPE_IDS.education,
    title: "Ta'lim",
    description: "O‘quv markazi, kurs, bog‘cha va ta’lim xizmatlari.",
    workspaceLabel: "Education workspace",
    primaryModule: MODULE_IDS.students,
    modules: [
      MODULE_IDS.dashboard,
      MODULE_IDS.inventory,
      MODULE_IDS.purchases,
      MODULE_IDS.crm,
      MODULE_IDS.finance,
      MODULE_IDS.reports,
      MODULE_IDS.hr,
      MODULE_IDS.students,
      MODULE_IDS.groups,
      MODULE_IDS.schedule,
      MODULE_IDS.integrations,
      MODULE_IDS.ai,
      MODULE_IDS.settings,
    ],
    dashboardType: "education",
  },

  [BUSINESS_TYPE_IDS.service]: {
    id: BUSINESS_TYPE_IDS.service,
    title: "Xizmat",
    description: "Servis, xizmat ko‘rsatish, buyurtma va mijoz ishlari.",
    workspaceLabel: "Service workspace",
    primaryModule: MODULE_IDS.orders,
    modules: [
      MODULE_IDS.dashboard,
      MODULE_IDS.pos,
      MODULE_IDS.products,
      MODULE_IDS.inventory,
      MODULE_IDS.purchases,
      MODULE_IDS.crm,
      MODULE_IDS.finance,
      MODULE_IDS.reports,
      MODULE_IDS.hr,
      MODULE_IDS.orders,
      MODULE_IDS.services,
      MODULE_IDS.integrations,
      MODULE_IDS.ai,
      MODULE_IDS.settings,
    ],
    dashboardType: "service",
  },

  [BUSINESS_TYPE_IDS.hotel]: {
    id: BUSINESS_TYPE_IDS.hotel,
    title: "Mehmonxona",
    description: "Xonalar, bronlar, mijozlar, to‘lovlar va xizmatlar.",
    workspaceLabel: "Hotel workspace",
    primaryModule: MODULE_IDS.bookings,
    modules: [
      MODULE_IDS.dashboard,
      MODULE_IDS.pos,
      MODULE_IDS.inventory,
      MODULE_IDS.purchases,
      MODULE_IDS.crm,
      MODULE_IDS.finance,
      MODULE_IDS.reports,
      MODULE_IDS.hr,
      MODULE_IDS.rooms,
      MODULE_IDS.bookings,
      MODULE_IDS.integrations,
      MODULE_IDS.ai,
      MODULE_IDS.settings,
    ],
    dashboardType: "hotel",
  },

  [BUSINESS_TYPE_IDS.clinic]: {
    id: BUSINESS_TYPE_IDS.clinic,
    title: "Klinika",
    description: "Bemorlar, shifokorlar, xizmatlar, dorilar va moliya.",
    workspaceLabel: "Clinic workspace",
    primaryModule: MODULE_IDS.patients,
    modules: [
      MODULE_IDS.dashboard,
      MODULE_IDS.pos,
      MODULE_IDS.medicines,
      MODULE_IDS.inventory,
      MODULE_IDS.purchases,
      MODULE_IDS.crm,
      MODULE_IDS.finance,
      MODULE_IDS.reports,
      MODULE_IDS.hr,
      MODULE_IDS.patients,
      MODULE_IDS.doctors,
      MODULE_IDS.integrations,
      MODULE_IDS.ai,
      MODULE_IDS.settings,
    ],
    dashboardType: "clinic",
  },
};

export const DEFAULT_BUSINESS_TYPE = BUSINESS_TYPE_IDS.retail;

export const getBusinessTypeById = (businessTypeId = DEFAULT_BUSINESS_TYPE) =>
  businessTypes[businessTypeId] || businessTypes[DEFAULT_BUSINESS_TYPE];

export const getBusinessModules = (businessTypeId = DEFAULT_BUSINESS_TYPE) =>
  getBusinessTypeById(businessTypeId).modules;
