import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Warehouse,
  ClipboardList,
  Users,
  Truck,
  Wallet,
  BarChart3,
  UserRoundCog,
  ShieldCheck,
  GitBranch,
  CheckSquare,
  CalendarDays,
  Bell,
  FileText,
  BadgePercent,
  Plug,
  Sparkles,
  Settings,
  Factory,
  Pill,
  GraduationCap,
  UsersRound,
  CalendarClock,
  Utensils,
  Table2,
  ClipboardCheck,
  BriefcaseBusiness,
  BedDouble,
  BookOpen,
  HeartPulse,
  Stethoscope,
} from "lucide-react";

export const MODULE_CATEGORIES = {
  core: "Core",
  commerce: "Commerce",
  operations: "Operations",
  finance: "Finance",
  people: "People",
  intelligence: "Intelligence",
  system: "System",
};

export const MODULE_IDS = {
  dashboard: "dashboard",
  pos: "pos",
  products: "products",
  inventory: "inventory",
  purchases: "purchases",
  crm: "crm",
  suppliers: "suppliers",
  finance: "finance",
  reports: "reports",
  hr: "hr",
  roles: "roles",
  branches: "branches",
  tasks: "tasks",
  calendar: "calendar",
  notifications: "notifications",
  documents: "documents",
  discounts: "discounts",
  integrations: "integrations",
  ai: "ai",
  settings: "settings",

  production: "production",
  medicines: "medicines",
  recipe: "recipe",
  tables: "tables",
  students: "students",
  groups: "groups",
  schedule: "schedule",
  orders: "orders",
  services: "services",
  rooms: "rooms",
  bookings: "bookings",
  patients: "patients",
  doctors: "doctors",
};

export const modules = {
  [MODULE_IDS.dashboard]: {
    id: MODULE_IDS.dashboard,
    title: "Boshqaruv paneli",
    description: "Biznes holatini real vaqt rejimida ko‘rish.",
    route: "/dashboard",
    icon: LayoutDashboard,
    category: MODULE_CATEGORIES.core,
    permission: "dashboard.view",
    order: 1,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.pos]: {
    id: MODULE_IDS.pos,
    title: "POS",
    description: "Savdo, to‘lov, chek va kassani boshqarish.",
    route: "/pos",
    icon: ShoppingCart,
    category: MODULE_CATEGORIES.commerce,
    permission: "pos.view",
    order: 2,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.products]: {
    id: MODULE_IDS.products,
    title: "Mahsulotlar",
    description: "Mahsulotlar, kategoriya, barcode va narxlar.",
    route: "/products",
    icon: Package,
    category: MODULE_CATEGORIES.commerce,
    permission: "products.view",
    order: 3,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.inventory]: {
    id: MODULE_IDS.inventory,
    title: "Ombor",
    description: "Qoldiq, kirim, chiqim va ombor harakatlari.",
    route: "/warehouse",
    icon: Warehouse,
    category: MODULE_CATEGORIES.operations,
    permission: "inventory.view",
    order: 4,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.purchases]: {
    id: MODULE_IDS.purchases,
    title: "Xaridlar",
    description: "Kirim, xarid buyurtmalari va tannarx nazorati.",
    route: "/purchases",
    icon: ClipboardList,
    category: MODULE_CATEGORIES.operations,
    permission: "purchases.view",
    order: 5,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.crm]: {
    id: MODULE_IDS.crm,
    title: "CRM",
    description: "Mijozlar, segmentlar va xarid tarixi.",
    route: "/crm",
    icon: Users,
    category: MODULE_CATEGORIES.commerce,
    permission: "crm.view",
    order: 6,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.suppliers]: {
    id: MODULE_IDS.suppliers,
    title: "Yetkazib beruvchilar",
    description: "Ta’minotchilar, qarzdorlik va yetkazib berish tarixi.",
    route: "/suppliers",
    icon: Truck,
    category: MODULE_CATEGORIES.operations,
    permission: "suppliers.view",
    order: 7,
    searchable: true,
    sidebar: true,
    dashboard: false,
    aiSupported: true,
  },

  [MODULE_IDS.finance]: {
    id: MODULE_IDS.finance,
    title: "Moliya",
    description: "Kassa, xarajat, foyda, qarz va to‘lovlar.",
    route: "/finance",
    icon: Wallet,
    category: MODULE_CATEGORIES.finance,
    permission: "finance.view",
    order: 8,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.reports]: {
    id: MODULE_IDS.reports,
    title: "Hisobotlar",
    description: "Savdo, foyda, ombor va moliyaviy hisobotlar.",
    route: "/reports",
    icon: BarChart3,
    category: MODULE_CATEGORIES.finance,
    permission: "reports.view",
    order: 9,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.hr]: {
    id: MODULE_IDS.hr,
    title: "Xodimlar HR",
    description: "Xodimlar, ish haqi, lavozim va davomat.",
    route: "/hr",
    icon: UserRoundCog,
    category: MODULE_CATEGORIES.people,
    permission: "hr.view",
    order: 10,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.roles]: {
    id: MODULE_IDS.roles,
    title: "Rollar va ruxsatlar",
    description: "Foydalanuvchi rollari va permission boshqaruvi.",
    route: "/roles",
    icon: ShieldCheck,
    category: MODULE_CATEGORIES.system,
    permission: "roles.view",
    order: 11,
    searchable: true,
    sidebar: true,
    dashboard: false,
    aiSupported: false,
  },

  [MODULE_IDS.branches]: {
    id: MODULE_IDS.branches,
    title: "Filiallar",
    description: "Filiallar, ish joylari va biznes lokatsiyalari.",
    route: "/branches",
    icon: GitBranch,
    category: MODULE_CATEGORIES.operations,
    permission: "branches.view",
    order: 12,
    searchable: true,
    sidebar: true,
    dashboard: false,
    aiSupported: true,
  },

  [MODULE_IDS.tasks]: {
    id: MODULE_IDS.tasks,
    title: "Vazifalar",
    description: "Jamoa vazifalari, deadline va workflow.",
    route: "/tasks",
    icon: CheckSquare,
    category: MODULE_CATEGORIES.people,
    permission: "tasks.view",
    order: 13,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.calendar]: {
    id: MODULE_IDS.calendar,
    title: "Kalendar",
    description: "Uchrashuvlar, jadval va biznes voqealari.",
    route: "/calendar",
    icon: CalendarDays,
    category: MODULE_CATEGORIES.people,
    permission: "calendar.view",
    order: 14,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.notifications]: {
    id: MODULE_IDS.notifications,
    title: "Bildirishnomalar",
    description: "Muhim ogohlantirishlar va real-time xabarlar.",
    route: "/notifications",
    icon: Bell,
    category: MODULE_CATEGORIES.system,
    permission: "notifications.view",
    order: 15,
    searchable: true,
    sidebar: false,
    dashboard: false,
    aiSupported: true,
  },

  [MODULE_IDS.documents]: {
    id: MODULE_IDS.documents,
    title: "Hujjatlar",
    description: "Shartnoma, invoice, chek va biznes hujjatlari.",
    route: "/documents",
    icon: FileText,
    category: MODULE_CATEGORIES.operations,
    permission: "documents.view",
    order: 16,
    searchable: true,
    sidebar: true,
    dashboard: false,
    aiSupported: true,
  },

  [MODULE_IDS.discounts]: {
    id: MODULE_IDS.discounts,
    title: "Aksiya va chegirmalar",
    description: "Promokod, chegirma va marketing aksiyalari.",
    route: "/discounts",
    icon: BadgePercent,
    category: MODULE_CATEGORIES.commerce,
    permission: "discounts.view",
    order: 17,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.integrations]: {
    id: MODULE_IDS.integrations,
    title: "Integratsiyalar",
    description: "Telegram, Click, Payme, API va tashqi servislar.",
    route: "/integrations",
    icon: Plug,
    category: MODULE_CATEGORIES.system,
    permission: "integrations.view",
    order: 18,
    searchable: true,
    sidebar: true,
    dashboard: false,
    aiSupported: true,
  },

  [MODULE_IDS.ai]: {
    id: MODULE_IDS.ai,
    title: "ZENIX AI",
    description: "AI tavsiyalar, tahlil va biznes yordamchi.",
    route: "/ai",
    icon: Sparkles,
    category: MODULE_CATEGORIES.intelligence,
    permission: "ai.view",
    order: 19,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
    premium: true,
  },

  [MODULE_IDS.settings]: {
    id: MODULE_IDS.settings,
    title: "Sozlamalar",
    description: "Workspace, profil, xavfsizlik va tizim sozlamalari.",
    route: "/settings",
    icon: Settings,
    category: MODULE_CATEGORIES.system,
    permission: "settings.view",
    order: 20,
    searchable: true,
    sidebar: true,
    dashboard: false,
    aiSupported: false,
  },

  [MODULE_IDS.production]: {
    id: MODULE_IDS.production,
    title: "Ishlab chiqarish",
    description: "Ishlab chiqarish jarayoni, xomashyo va tayyor mahsulot.",
    route: "/production",
    icon: Factory,
    category: MODULE_CATEGORIES.operations,
    permission: "production.view",
    order: 21,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.medicines]: {
    id: MODULE_IDS.medicines,
    title: "Dorilar",
    description: "Dori nomlari, seriya, yaroqlilik muddati va qoldiq.",
    route: "/medicines",
    icon: Pill,
    category: MODULE_CATEGORIES.commerce,
    permission: "medicines.view",
    order: 22,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.recipe]: {
    id: MODULE_IDS.recipe,
    title: "Retseptura",
    description: "Taom tannarxi, ingredientlar va porsiya hisob-kitobi.",
    route: "/recipe",
    icon: Utensils,
    category: MODULE_CATEGORIES.operations,
    permission: "recipe.view",
    order: 23,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.tables]: {
    id: MODULE_IDS.tables,
    title: "Stol boshqaruvi",
    description: "Stollar bandligi, zal holati va buyurtmalar.",
    route: "/tables",
    icon: Table2,
    category: MODULE_CATEGORIES.operations,
    permission: "tables.view",
    order: 24,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.students]: {
    id: MODULE_IDS.students,
    title: "Talabalar",
    description: "Talabalar bazasi, to‘lovlar va o‘quv holati.",
    route: "/students",
    icon: GraduationCap,
    category: MODULE_CATEGORIES.people,
    permission: "students.view",
    order: 25,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.groups]: {
    id: MODULE_IDS.groups,
    title: "Guruhlar",
    description: "Guruhlar, ustozlar va o‘quvchilar taqsimoti.",
    route: "/groups",
    icon: UsersRound,
    category: MODULE_CATEGORIES.people,
    permission: "groups.view",
    order: 26,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.schedule]: {
    id: MODULE_IDS.schedule,
    title: "Dars jadvali",
    description: "Dars vaqtlari, ustozlar va xonalar jadvali.",
    route: "/schedule",
    icon: CalendarClock,
    category: MODULE_CATEGORIES.people,
    permission: "schedule.view",
    order: 27,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.orders]: {
    id: MODULE_IDS.orders,
    title: "Buyurtmalar",
    description: "Xizmat buyurtmalari, statuslar va bajarilish jarayoni.",
    route: "/orders",
    icon: ClipboardCheck,
    category: MODULE_CATEGORIES.operations,
    permission: "orders.view",
    order: 28,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.services]: {
    id: MODULE_IDS.services,
    title: "Xizmatlar",
    description: "Xizmat turlari, narxlar va bajarilish muddati.",
    route: "/services",
    icon: BriefcaseBusiness,
    category: MODULE_CATEGORIES.commerce,
    permission: "services.view",
    order: 29,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.rooms]: {
    id: MODULE_IDS.rooms,
    title: "Xonalar",
    description: "Xonalar, bandlik, status va narxlar.",
    route: "/rooms",
    icon: BedDouble,
    category: MODULE_CATEGORIES.operations,
    permission: "rooms.view",
    order: 30,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.bookings]: {
    id: MODULE_IDS.bookings,
    title: "Bronlar",
    description: "Bronlar, kelish-ketish va to‘lov statuslari.",
    route: "/bookings",
    icon: BookOpen,
    category: MODULE_CATEGORIES.operations,
    permission: "bookings.view",
    order: 31,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.patients]: {
    id: MODULE_IDS.patients,
    title: "Bemorlar",
    description: "Bemor kartasi, tashriflar va xizmat tarixi.",
    route: "/patients",
    icon: HeartPulse,
    category: MODULE_CATEGORIES.people,
    permission: "patients.view",
    order: 32,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },

  [MODULE_IDS.doctors]: {
    id: MODULE_IDS.doctors,
    title: "Shifokorlar",
    description: "Shifokorlar, jadval, xizmatlar va qabul holati.",
    route: "/doctors",
    icon: Stethoscope,
    category: MODULE_CATEGORIES.people,
    permission: "doctors.view",
    order: 33,
    searchable: true,
    sidebar: true,
    dashboard: true,
    aiSupported: true,
  },
};

export const getModuleById = (moduleId) => modules[moduleId];

export const getModulesByIds = (moduleIds = []) =>
  moduleIds
    .map((moduleId) => modules[moduleId])
    .filter(Boolean)
    .sort((a, b) => a.order - b.order);

export const getSidebarModules = (moduleIds = []) =>
  getModulesByIds(moduleIds).filter((module) => module.sidebar);

export const getSearchableModules = (moduleIds = []) =>
  getModulesByIds(moduleIds).filter((module) => module.searchable);
