import {
  Award,
  Banknote,
  BarChart3,
  CalendarClock,
  ClipboardCheck,
  FileClock,
  GitBranch,
  UserPlus,
  Users,
} from "lucide-react";

export const hrHubConfig = {
  id: "hr",
  title: "Xodimlar HR",
  description: "Xodimlar, davomat, payroll, recruitment va HR nazorat yo'nalishlari.",
  sections: [
    {
      id: "employees",
      title: "Xodimlar",
      items: [
        {
          id: "hr-employees",
          title: "Xodimlar ro'yxati",
          description: "Barcha xodimlarni ko'rish, qidirish va boshqarish.",
          icon: Users,
          route: "/hr/employees",
          order: 1,
        },
        {
          id: "hr-new-employee",
          title: "Yangi xodim",
          description: "Yangi xodim profilini yaratish.",
          icon: UserPlus,
          route: "/hr/employee-create",
          permission: { key: "employee.edit", fallback: "disabled" },
          order: 2,
        },
        {
          id: "hr-departments",
          title: "Bo'limlar va lavozimlar",
          description: "Bo'lim, lavozim va filial tuzilmasini boshqarish.",
          icon: GitBranch,
          route: "/hr/departments",
          order: 3,
        },
      ],
    },
    {
      id: "workflows",
      title: "Ish jarayonlari",
      items: [
        {
          id: "hr-attendance",
          title: "Davomat",
          description: "Xodimlarning kirish, chiqish va ish vaqtini kuzatish.",
          icon: CalendarClock,
          route: "/hr/attendance",
          order: 1,
        },
        {
          id: "hr-shifts",
          title: "Smenalar",
          description: "Smena jadvallari va xodim biriktirishlarini boshqarish.",
          icon: CalendarClock,
          route: "/hr/shifts",
          order: 2,
        },
        {
          id: "hr-leaves",
          title: "Ta'tillar",
          description: "Ta'til arizalarini ko'rish va tasdiqlash.",
          icon: FileClock,
          route: "/hr/leaves",
          permission: { key: "leave.approve", fallback: "enabled" },
          order: 3,
        },
        {
          id: "hr-tasks",
          title: "Vazifalar",
          description: "Xodimlarga berilgan vazifalar va statuslarni boshqarish.",
          icon: ClipboardCheck,
          route: "/hr/tasks",
          order: 4,
        },
      ],
    },
    {
      id: "finance-growth",
      title: "Moliya va rivojlanish",
      items: [
        {
          id: "hr-payroll",
          title: "Payroll",
          description: "Oylik, bonus, jarima va ushlab qolishlarni hisoblash.",
          icon: Banknote,
          route: "/hr/payroll",
          permission: { key: "salary.view", fallback: "disabled" },
          order: 1,
        },
        {
          id: "hr-performance",
          title: "Performance",
          description: "Xodim KPI, baholash va samaradorlik ko'rsatkichlari.",
          icon: Award,
          route: "/hr/performance",
          order: 2,
        },
        {
          id: "hr-recruitment",
          title: "Recruitment",
          description: "Vakansiyalar, nomzodlar va ishga qabul jarayoni.",
          icon: UserPlus,
          route: "/hr/recruitment",
          order: 3,
        },
      ],
    },
    {
      id: "analytics",
      title: "Tahlil va boshqaruv",
      items: [
        {
          id: "hr-overview",
          title: "HR Dashboard",
          description: "Headcount, turnover, payroll va davomat umumiy ko'rinishi.",
          icon: BarChart3,
          route: "/hr/overview",
          order: 1,
        },
        {
          id: "hr-reports",
          title: "HR reports",
          description: "Hisobotlar, audit va bildirishnomalar.",
          icon: FileClock,
          route: "/hr/reports",
          order: 2,
        },
      ],
    },
  ],
};
